import newrelic from 'newrelic';
import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (newrelic.agent.collector.isConnected() === false) {
    await new Promise((resolve) => {
      newrelic.agent.on("connected", resolve)
    })
  }

  const browserTimingHeader = newrelic.getBrowserTimingHeader({
    hasToRemoveScriptWrapper: true,
    allowTransactionlessInjection: true,
  });

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script
          // We have to set an id for inline scripts.
          // See https://nextjs.org/docs/app/building-your-application/optimizing/scripts#inline-scripts
          id="nr-browser-agent"
          // By setting the strategy to "beforeInteractive" we guarantee that
          // the script will be added to the document's `head` element.
          strategy="beforeInteractive"
          // The body of the script element comes from the async evaluation
          // of `getInitialProps`. We use the special
          // `dangerouslySetInnerHTML` to provide that element body. Since
          // it requires an object with an `__html` property, we pass in an
          // object literal.
          dangerouslySetInnerHTML={{__html: browserTimingHeader}}
        />
        {children}
      </body>
    </html>
  );
}
